// Generated by scripts/generate-models.ts. Static require paths keep the JSON
// embeddable by bundlers while materialization stays lazy per provider.
export function loadProviderModels(provider: string): Record<string, unknown> | undefined {
	switch (provider) {
		case "aiand":
			return require("./models/aiand.json") as Record<string, unknown>;
		case "aimlapi":
			return require("./models/aimlapi.json") as Record<string, unknown>;
		case "alibaba-coding-plan":
			return require("./models/alibaba-coding-plan.json") as Record<string, unknown>;
		case "alibaba-token-plan":
			return require("./models/alibaba-token-plan.json") as Record<string, unknown>;
		case "amazon-bedrock":
			return require("./models/amazon-bedrock.json") as Record<string, unknown>;
		case "anthropic":
			return require("./models/anthropic.json") as Record<string, unknown>;
		case "azure":
			return require("./models/azure.json") as Record<string, unknown>;
		case "baseten":
			return require("./models/baseten.json") as Record<string, unknown>;
		case "bedrock-mantle":
			return require("./models/bedrock-mantle.json") as Record<string, unknown>;
		case "cerebras":
			return require("./models/cerebras.json") as Record<string, unknown>;
		case "cloudflare-ai-gateway":
			return require("./models/cloudflare-ai-gateway.json") as Record<string, unknown>;
		case "coreweave":
			return require("./models/coreweave.json") as Record<string, unknown>;
		case "cursor":
			return require("./models/cursor.json") as Record<string, unknown>;
		case "deepseek":
			return require("./models/deepseek.json") as Record<string, unknown>;
		case "devin":
			return require("./models/devin.json") as Record<string, unknown>;
		case "firepass":
			return require("./models/firepass.json") as Record<string, unknown>;
		case "fireworks":
			return require("./models/fireworks.json") as Record<string, unknown>;
		case "github-copilot":
			return require("./models/github-copilot.json") as Record<string, unknown>;
		case "gitlab-duo":
			return require("./models/gitlab-duo.json") as Record<string, unknown>;
		case "gitlab-duo-agent":
			return require("./models/gitlab-duo-agent.json") as Record<string, unknown>;
		case "gmi-cloud":
			return require("./models/gmi-cloud.json") as Record<string, unknown>;
		case "google":
			return require("./models/google.json") as Record<string, unknown>;
		case "google-antigravity":
			return require("./models/google-antigravity.json") as Record<string, unknown>;
		case "google-gemini-cli":
			return require("./models/google-gemini-cli.json") as Record<string, unknown>;
		case "google-vertex":
			return require("./models/google-vertex.json") as Record<string, unknown>;
		case "groq":
			return require("./models/groq.json") as Record<string, unknown>;
		case "huggingface":
			return require("./models/huggingface.json") as Record<string, unknown>;
		case "kilo":
			return require("./models/kilo.json") as Record<string, unknown>;
		case "kimi-code":
			return require("./models/kimi-code.json") as Record<string, unknown>;
		case "meta":
			return require("./models/meta.json") as Record<string, unknown>;
		case "minimax":
			return require("./models/minimax.json") as Record<string, unknown>;
		case "minimax-cn":
			return require("./models/minimax-cn.json") as Record<string, unknown>;
		case "minimax-code":
			return require("./models/minimax-code.json") as Record<string, unknown>;
		case "minimax-code-cn":
			return require("./models/minimax-code-cn.json") as Record<string, unknown>;
		case "mistral":
			return require("./models/mistral.json") as Record<string, unknown>;
		case "moonshot":
			return require("./models/moonshot.json") as Record<string, unknown>;
		case "nanogpt":
			return require("./models/nanogpt.json") as Record<string, unknown>;
		case "novita":
			return require("./models/novita.json") as Record<string, unknown>;
		case "nvidia":
			return require("./models/nvidia.json") as Record<string, unknown>;
		case "ollama-cloud":
			return require("./models/ollama-cloud.json") as Record<string, unknown>;
		case "openai":
			return require("./models/openai.json") as Record<string, unknown>;
		case "openai-codex":
			return require("./models/openai-codex.json") as Record<string, unknown>;
		case "opencode":
			return require("./models/opencode.json") as Record<string, unknown>;
		case "opencode-go":
			return require("./models/opencode-go.json") as Record<string, unknown>;
		case "opencode-zen":
			return require("./models/opencode-zen.json") as Record<string, unknown>;
		case "openrouter":
			return require("./models/openrouter.json") as Record<string, unknown>;
		case "qianfan":
			return require("./models/qianfan.json") as Record<string, unknown>;
		case "qwen-portal":
			return require("./models/qwen-portal.json") as Record<string, unknown>;
		case "sakana":
			return require("./models/sakana.json") as Record<string, unknown>;
		case "synthetic":
			return require("./models/synthetic.json") as Record<string, unknown>;
		case "together":
			return require("./models/together.json") as Record<string, unknown>;
		case "umans":
			return require("./models/umans.json") as Record<string, unknown>;
		case "venice":
			return require("./models/venice.json") as Record<string, unknown>;
		case "vercel-ai-gateway":
			return require("./models/vercel-ai-gateway.json") as Record<string, unknown>;
		case "wafer-serverless":
			return require("./models/wafer-serverless.json") as Record<string, unknown>;
		case "xai":
			return require("./models/xai.json") as Record<string, unknown>;
		case "xai-oauth":
			return require("./models/xai-oauth.json") as Record<string, unknown>;
		case "xiaomi":
			return require("./models/xiaomi.json") as Record<string, unknown>;
		case "xiaomi-token-plan-ams":
			return require("./models/xiaomi-token-plan-ams.json") as Record<string, unknown>;
		case "xiaomi-token-plan-cn":
			return require("./models/xiaomi-token-plan-cn.json") as Record<string, unknown>;
		case "xiaomi-token-plan-sgp":
			return require("./models/xiaomi-token-plan-sgp.json") as Record<string, unknown>;
		case "zai":
			return require("./models/zai.json") as Record<string, unknown>;
		case "zenmux":
			return require("./models/zenmux.json") as Record<string, unknown>;
		case "zhipu-coding-plan":
			return require("./models/zhipu-coding-plan.json") as Record<string, unknown>;
		default:
			return undefined;
	}
}
