/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DesktopSession {
  constructor(options?: DesktopSessionOptions | undefined | null)
  get capabilities(): DesktopCapabilities
  listDisplays(): Promise<Array<DesktopDisplay>>
  listWindows(): Promise<Array<DesktopWindow>>
  capture(target: string, caps?: CaptureCaps | undefined | null): Promise<DesktopCapture>
  click(target: string, x: number, y: number, opts?: PointerOptions | undefined | null): Promise<undefined>
  moveMouse(target: string, x: number, y: number, opts?: PointerOptions | undefined | null): Promise<undefined>
  drag(target: string, path: Array<DesktopPoint>, opts?: PointerOptions | undefined | null): Promise<undefined>
  scroll(target: string, x: number, y: number, dx: number, dy: number, opts?: PointerOptions | undefined | null): Promise<undefined>
  typeText(target: string, text: string, opts?: PointerOptions | undefined | null): Promise<undefined>
  keyChord(target: string, keys: Array<string>, opts?: PointerOptions | undefined | null): Promise<undefined>
  raiseWindow(windowId: string): Promise<undefined>
  axSnapshot(target: string, opts?: AxSnapshotOptions | undefined | null): Promise<AxSnapshot>
  axQuery(target: string, query: AxQuery): Promise<Array<AxNode>>
  axElementAt(target: string, x: number, y: number): Promise<AxNode | undefined | null>
  axFocused(): Promise<AxNode | undefined | null>
  axNode(reference: string): Promise<AxNode>
  axAttributes(reference: string): Promise<Array<[string, string]>>
  axChildren(reference: string): Promise<Array<AxNode>>
  axParent(reference: string): Promise<AxNode | undefined | null>
  axPerform(reference: string, action: string): Promise<undefined>
  axSetValue(reference: string, value: string): Promise<undefined>
  axFocus(reference: string): Promise<undefined>
  axClick(reference: string, opts?: PointerOptions | undefined | null): Promise<undefined>
  close(): Promise<undefined>
}

export declare class FileLock {
  static tryAcquire(path: string): FileLock
  get acquired(): boolean
  release(): void
}

export declare class HighlightStream {
  constructor(lang: string | undefined | null, colors: HighlightColors)
  get supported(): boolean
  push(chunk: string): string
}

export declare class MacAppearanceObserver {
  static start(callback: (err: null | Error, appearance: MacOSAppearance) => void): MacAppearanceObserver
  stop(): void
}

export declare class MacOSPowerAssertion {
  static start(options?: MacOSPowerAssertionOptions | undefined | null): MacOSPowerAssertion
  stop(): void
}

export declare class Process {
  static fromPid(pid: number): Process | null
  static fromPath(path: string): Array<Process>
  get pid(): number
  get ppid(): number | null
  args(): Array<string>
  killTree(signal?: number | undefined | null): number
  terminate(options?: ProcessTerminateOptions | undefined | null): Promise<boolean>
  waitForExit(options?: ProcessWaitOptions | undefined | null): Promise<boolean>
  groupId(): number | null
  children(): Array<Process>
  status(): ProcessStatus
}

export declare class PtySession {
  constructor()
  start(options: PtyStartOptions, onChunk?: ((error: Error | null, chunk: string) => void) | undefined | null, onStart?: ((error: Error | null, pid: number) => void) | undefined | null): Promise<PtyRunResult>
  startArgv(options: PtyArgvStartOptions, onChunk?: ((error: Error | null, chunk: string) => void) | undefined | null, onStart?: ((error: Error | null, pid: number) => void) | undefined | null): Promise<PtyRunResult>
  write(data: string): void
  resize(cols: number, rows: number): void
  kill(): void
}

export declare class Shell {
  constructor(options?: ShellOptions | undefined | null)
  run(options: ShellRunOptions, onChunk?: ((error: Error | null, chunk: string) => void) | undefined | null, xdDispatcher?: ((request: string) => Promise<string>) | undefined | null): Promise<ShellRunResult>
  abort(): Promise<void>
  liveBackgroundJobCount(): Promise<number>
}

export declare class TtyWriter {
  constructor(fd: number)
  write(data: string): number
  pending(): number
  get dead(): boolean
  flushSync(timeoutMs: number): boolean
  stop(flushTimeoutMs: number): void
}

export declare function __ompInstallTokioRuntime(): void

export declare function __piNativesV18_0_2(): void

export declare function astEdit(options: AstReplaceOptions): Promise<AstReplaceResult>

export interface AstFindMatch {
  path: string
  text: string
  byteStart: number
  byteEnd: number
  startLine: number
  startColumn: number
  endLine: number
  endColumn: number
  metaVariables?: Record<string, string>
}

export interface AstFindOptions {
  patterns?: Array<string>
  lang?: string
  path?: string
  glob?: string
  selector?: string
  strictness?: AstMatchStrictness
  limit?: number
  offset?: number
  includeMeta?: boolean
  context?: number
  signal?: unknown
  timeoutMs?: number
}

export interface AstFindResult {
  matches: Array<AstFindMatch>
  totalMatches: number
  filesWithMatches: number
  filesSearched: number
  limitReached: boolean
  parseErrors?: Array<string>
}

export declare function astGrep(options: AstFindOptions): Promise<AstFindResult>

export declare function astMatch(options: AstMatchOptions): Promise<AstMatchResult>

export interface AstMatchOptions {
  source: string
  lang: string
  patterns: Array<string>
  selector?: string
  strictness?: AstMatchStrictness
  limit?: number
  offset?: number
  includeMeta?: boolean
  signal?: unknown
  timeoutMs?: number
}

export interface AstMatchResult {
  matches: Array<AstFindMatch>
  totalMatches: number
  limitReached: boolean
  parseErrors?: Array<string>
}

export declare enum AstMatchStrictness {
  Cst = 'cst',
  Smart = 'smart',
  Ast = 'ast',
  Relaxed = 'relaxed',
  Signature = 'signature',
  Template = 'template'
}

export interface AstReplaceChange {
  path: string
  before: string
  after: string
  byteStart: number
  byteEnd: number
  deletedLength: number
  startLine: number
  startColumn: number
  endLine: number
  endColumn: number
}

export interface AstReplaceFileChange {
  path: string
  count: number
}

export interface AstReplaceOptions {
  rewrites?: Record<string, string>
  lang?: string
  path?: string
  glob?: string
  selector?: string
  strictness?: AstMatchStrictness
  dryRun?: boolean
  maxReplacements?: number
  maxFiles?: number
  failOnParseError?: boolean
  signal?: unknown
  timeoutMs?: number
}

export interface AstReplaceResult {
  changes: Array<AstReplaceChange>
  fileChanges: Array<AstReplaceFileChange>
  totalReplacements: number
  filesTouched: number
  filesSearched: number
  applied: boolean
  limitReached: boolean
  parseErrors?: Array<string>
}

export interface AxNode {
  ref: string
  role: string
  nativeRole: string
  title?: string
  value?: string
  description?: string
  enabled: boolean
  focused: boolean
  x?: number
  y?: number
  width?: number
  height?: number
  actions?: Array<string>
  childCount: number
}

export interface AxQuery {
  role?: string
  title?: string
  value?: string
  limit?: number
}

export interface AxSnapshot {
  text: string
  nodeCount: number
  truncated: boolean
}

export interface AxSnapshotOptions {
  maxDepth?: number
  maxNodes?: number
  all?: boolean
}

export interface BlockRange {
  startLine: number
  endLine: number
}

export declare function blockRangeAt(options: BlockRangeOptions): BlockRange | null

export interface BlockRangeOptions {
  code: string
  lang?: string
  path?: string
  line: number
}

export interface CaptureCaps {
  maxWidth?: number
  maxHeight?: number
}

export interface ClipboardImage {
  data: Uint8Array
  mimeType: string
}

export declare function codeOutline(options: OutlineOptions): OutlineResult

export interface ContextLine {
  lineNumber: number
  line: string
}

export declare function copyToClipboard(text: string): void

export declare function cosineSimilarityPairs(vectors: Float64Array, count: number, dim: number, threshold: number): Uint32Array

export declare function countTokens(input: string | string[], encoding?: Encoding | undefined | null): number

export interface DesktopCapabilities {
  backend: string
  displayServer?: string
  capture: boolean
  input: boolean
  ax: boolean
  backgroundWindowInput: boolean
  deliveryModes: Array<string>
  capturePermission: string
  inputPermission: string
  axPermission: string
  displayCount: number
}

export interface DesktopCapture {
  data: Uint8Array
  width: number
  height: number
  sourceWidth: number
  sourceHeight: number
  target: string
  displays: Array<DesktopDisplay>
  backend: string
  displayServer?: string
}

export interface DesktopDisplay {
  id: string
  name: string
  x: number
  y: number
  width: number
  height: number
  scale: number
  pixelX: number
  pixelY: number
  pixelWidth: number
  pixelHeight: number
  isPrimary: boolean
}

export interface DesktopPoint {
  x: number
  y: number
}

export interface DesktopSessionOptions {
  display?: string
}

export interface DesktopWindow {
  id: string
  title: string
  app: string
  pid?: number
  x: number
  y: number
  width: number
  height: number
  focused: boolean
}

export declare function detectMacOSAppearance(): MacOSAppearance | null

export declare function deviceCheckGenerateToken(): Promise<DeviceCheckTokenResult>

export interface DeviceCheckTokenResult {
  supported: boolean
  tokenBase64?: string
  error?: string
  latencyMs: number
}

export interface DiffChange {
  value: string
  count: number
  added: boolean
  removed: boolean
}

export declare function diffLineRuns(oldText: string, newText: string): Array<DiffRun>

export declare function diffLines(oldText: string, newText: string): Array<DiffChange>

export interface DiffRun {
  count: number
  added: boolean
  removed: boolean
}

export declare function diffWords(oldText: string, newText: string): Array<DiffChange>

export declare enum Ellipsis {
  Unicode = 0,
  Ascii = 1,
  Omit = 2
}

export declare function enclosingBlockBoundaries(options: EnclosingBoundaryOptions): Array<number> | null

export interface EnclosingBoundaryOptions {
  code: string
  lang?: string
  path?: string
  ranges: Array<LineRange>
}

export declare function encodeSixel(bytes: Uint8Array, targetWidthPx: number, targetHeightPx: number): string

export declare enum Encoding {
  O200kBase = 'O200kBase',
  Cl100kBase = 'Cl100kBase',
  ClaudeV3 = 'ClaudeV3',
  ClaudeV47 = 'ClaudeV47',
  ClaudeV5 = 'ClaudeV5',
  ClaudeV5Sonnet = 'ClaudeV5Sonnet',
  Qwen3 = 'Qwen3',
  DeepSeekV3 = 'DeepSeekV3',
  KimiK2 = 'KimiK2',
  Glm5 = 'Glm5'
}

export declare function executeShell(options: ShellExecuteOptions, onChunk?: ((error: Error | null, chunk: string) => void) | undefined | null): Promise<ShellRunResult>

export declare function extractSegments(line: string, beforeEnd: number, afterStart: number, afterLen: number, strictAfter: boolean, tabWidth: number): ExtractSegmentsResult

export interface ExtractSegmentsResult {
  before: string
  beforeWidth: number
  after: string
  afterWidth: number
}

export declare enum FileType {
  File = 1,
  Dir = 2,
  Symlink = 3
}

export interface FsObservation {
  path: string
  kind: FsObservationKind
  mtimeNs?: string
  size?: number
}

export declare enum FsObservationKind {
  Read = 'read',
  Write = 'write'
}

export declare function fuzzyFind(options: FuzzyFindOptions): Promise<FuzzyFindResult>

export interface FuzzyFindMatch {
  path: string
  isDirectory: boolean
  score: number
}

export interface FuzzyFindOptions {
  query: string
  path: string
  hidden?: boolean
  gitignore?: boolean
  cache?: boolean
  maxResults?: number
  signal?: unknown
  timeoutMs?: number
}

export interface FuzzyFindResult {
  matches: Array<FuzzyFindMatch>
  totalMatches: number
}

export declare function getSupportedLanguages(): Array<string>

export declare function getWorkProfile(lastSeconds: number): WorkProfile

export declare function glob(options: GlobOptions, onMatch?: ((error: Error | null, match: GlobMatch) => void) | undefined | null): Promise<GlobResult>

export interface GlobMatch {
  path: string
  fileType: FileType
  mtime?: number
  size?: number
}

export interface GlobOptions {
  pattern: string
  path: string
  fileType?: FileType
  recursive?: boolean
  hidden?: boolean
  maxResults?: number
  gitignore?: boolean
  cache?: boolean
  sortByMtime?: boolean
  includeNodeModules?: boolean
  signal?: unknown
  timeoutMs?: number
}

export interface GlobResult {
  matches: Array<GlobMatch>
  totalMatches: number
}

export declare function grep(options: GrepOptions, onMatch?: ((error: Error | null, match: GrepMatch) => void) | undefined | null): Promise<GrepResult>

export interface GrepMatch {
  path: string
  lineNumber: number
  line: string
  contextBefore?: Array<ContextLine>
  contextAfter?: Array<ContextLine>
  truncated?: boolean
  matchCount?: number
}

export interface GrepOptions {
  pattern: string
  path: string
  glob?: string
  type?: string
  ignoreCase?: boolean
  multiline?: boolean
  hidden?: boolean
  gitignore?: boolean
  maxCount?: number
  offset?: number
  contextBefore?: number
  contextAfter?: number
  context?: number
  maxColumns?: number
  mode?: GrepOutputMode
  maxCountPerFile?: number
  signal?: unknown
  timeoutMs?: number
}

export declare enum GrepOutputMode {
  Content = 'content',
  Count = 'count',
  FilesWithMatches = 'filesWithMatches'
}

export interface GrepResult {
  matches: Array<GrepMatch>
  totalMatches: number
  filesWithMatches: number
  filesSearched: number
  limitReached?: boolean
  skippedOversized?: number
}

export declare function hasMatch(content: string | Uint8Array, pattern: string | Uint8Array, ignoreCase?: boolean | undefined | null, multiline?: boolean | undefined | null): boolean

export declare function highlightCode(code: string, lang: string | undefined | null, colors: HighlightColors): string

export interface HighlightColors {
  comment: string
  keyword: string
  function: string
  variable: string
  string: string
  number: string
  type: string
  operator: string
  punctuation: string
  inserted?: string
  deleted?: string
}

export declare function htmlToMarkdown(html: string, options?: HtmlToMarkdownOptions | undefined | null): Promise<string>

export interface HtmlToMarkdownOptions {
  cleanContent?: boolean
  skipImages?: boolean
}

export declare function invalidateFsScanCache(path?: string | undefined | null): void

export declare function isoBackend(): IsoBackendKind

export declare enum IsoBackendKind {
  Apfs = 0,
  Btrfs = 1,
  Zfs = 2,
  LinuxReflink = 3,
  Overlayfs = 4,
  Rcopy = 7
}

export declare enum IsoChangeKind {
  Added = 0,
  Modified = 1,
  Removed = 2
}

export declare function isoDiff(lower: string, merged: string): Promise<IsoDiff>

export interface IsoDiff {
  files: Array<IsoFileChange>
}

export interface IsoFileChange {
  path: string
  op: IsoChangeKind
  diff?: string
}

export declare function isoIsUnavailableError(message: string): boolean

export declare function isoProbe(kind?: IsoBackendKind | undefined | null): IsoProbeResult

export interface IsoProbeResult {
  available: boolean
  reason?: string
  kind: IsoBackendKind
}

export declare function isoResolve(preferred?: IsoBackendKind | undefined | null): IsoResolveResult

export interface IsoResolveResult {
  kind: IsoBackendKind
  candidates: Array<IsoBackendKind>
  fellBack: boolean
  reason?: string
}

export declare function isoStart(kind: IsoBackendKind | undefined | null, lower: string, merged: string): Promise<void>

export declare function isoStop(kind: IsoBackendKind | undefined | null, merged: string): Promise<void>

export declare enum KeyEventType {
  Press = 1,
  Repeat = 2,
  Release = 3
}

export interface LineRange {
  startLine: number
  endLine: number
}

export declare function listWorkspace(options: ListWorkspaceOptions): Promise<ListWorkspaceResult>

export interface ListWorkspaceOptions {
  path: string
  maxDepth: number
  hidden?: boolean
  gitignore?: boolean
  collectAgentsMd?: boolean
  timeoutMs?: number
  signal?: unknown
}

export interface ListWorkspaceResult {
  entries: Array<GlobMatch>
  agentsMdFiles: Array<string>
  truncated: boolean
}

export declare enum MacOSAppearance {
  Dark = 'dark',
  Light = 'light'
}

export declare function macOSAutocorrectWord(text: string, start: number, length: number): Promise<string | null>

export declare function macOSCheckSpelling(text: string): Promise<Array<SpellingRange>>

export declare function macOSCompleteWord(text: string, start: number, length: number): Promise<Array<string>>

export interface MacOSPowerAssertionOptions {
  reason?: string
  idle?: boolean
  system?: boolean
  user?: boolean
  display?: boolean
}

export declare function macOSSpellCheckerAvailable(): boolean

export declare function macOSSpellingGuesses(text: string, start: number, length: number): Promise<Array<string>>

export interface Match {
  lineNumber: number
  line: string
  contextBefore?: Array<ContextLine>
  contextAfter?: Array<ContextLine>
  truncated?: boolean
}

export declare function matchesKey(data: string, keyId: string, kittyProtocolActive: boolean): boolean

export declare function matchesKittySequence(data: string, expectedCodepoint: number, expectedModifier: number): boolean

export declare function matchesLegacySequence(data: string, keyName: string): boolean

export interface MinimizerOptions {
  enabled?: boolean
  settingsPath?: string
  settingsHash?: string
  only?: Array<string>
  except?: Array<string>
  maxCaptureBytes?: number
  sourceOutlineLevel?: string
  legacyFilters?: boolean
}

export interface MinimizerResult {
  filter: string
  text: string
  originalText: string
  inputBytes: number
  outputBytes: number
}

export declare function mmrRerankIndices(contents: Array<string>, scores: Float64Array, lambdaParam: number, topK: number): Uint32Array

export declare function nodeChainAt(options: BlockRangeOptions): Array<NodeSpan> | null

export interface NodeSpan {
  startLine: number
  endLine: number
  kind: string
}

export interface OutlineEntry {
  kind: string
  modifier?: string
  name?: string
  detail?: string
  doc?: string
  notes: Array<string>
  asks: Array<string>
  line: number
  children: Array<OutlineEntry>
}

export interface OutlineOptions {
  code: string
  lang?: string
  path?: string
}

export interface OutlineResult {
  language?: string
  parsed: boolean
  entries: Array<OutlineEntry>
}

export interface ParsedKittyResult {
  codepoint: number
  shiftedKey?: number
  baseLayoutKey?: number
  modifier: number
  eventType?: KeyEventType
}

export declare function parseKey(data: string, kittyProtocolActive: boolean): string | null

export declare function parseKittySequence(data: string): ParsedKittyResult | null

export interface PatchHunk {
  oldStart: number
  oldLines: number
  newStart: number
  newLines: number
  lines: Array<string>
}

export interface PdfMarkdownResult {
  markdown: string
  title?: string
  pageCount: number
  pagesNeedingOcr: Array<number>
  hasEncodingIssues: boolean
}

export declare function pdfToMarkdown(input: Uint8Array): Promise<PdfMarkdownResult>

export interface PointerOptions {
  button?: string
  count?: number
  modifiers?: Array<string>
  deliveryMode?: string
}

export declare enum ProcessStatus {
  Running = 'running',
  Exited = 'exited'
}

export interface ProcessTerminateOptions {
  group?: boolean
  gracefulMs?: number
  timeoutMs?: number
  signal?: unknown
}

export interface ProcessWaitOptions {
  timeoutMs?: number
  signal?: unknown
}

export interface PtyArgvStartOptions {
  application: string
  args: Array<string>
  cwd?: string
  env?: Record<string, string>
  timeoutMs?: number
  signal?: unknown
  cols?: number
  rows?: number
}

export interface PtyRunResult {
  exitCode?: number
  cancelled: boolean
  timedOut: boolean
}

export interface PtyStartOptions {
  command: string
  cwd?: string
  env?: Record<string, string>
  timeoutMs?: number
  signal?: unknown
  cols?: number
  rows?: number
  shell?: string
}

export declare function readImageFromClipboard(): Promise<ClipboardImage | undefined | null>

export declare function search(content: string | Uint8Array, options: SearchOptions): SearchResult

export interface SearchOptions {
  pattern: string
  ignoreCase?: boolean
  multiline?: boolean
  maxCount?: number
  offset?: number
  contextBefore?: number
  contextAfter?: number
  context?: number
  maxColumns?: number
  mode?: GrepOutputMode
}

export interface SearchResult {
  matches: Array<Match>
  matchCount: number
  limitReached: boolean
  error?: string
}

export declare function setHangulCompatJamoWidthOverride(value: number): void

export interface ShellExecuteOptions {
  command: string
  cwd?: string
  env?: Record<string, string>
  sessionEnv?: Record<string, string>
  timeoutMs?: number
  snapshotPath?: string
  minimizer?: MinimizerOptions
  signal?: unknown
}

export interface ShellOptions {
  sessionEnv?: Record<string, string>
  snapshotPath?: string
  minimizer?: MinimizerOptions
}

export interface ShellRunOptions {
  command: string
  cwd?: string
  env?: Record<string, string>
  timeoutMs?: number
  xdCallId?: string
  signal?: unknown
}

export interface ShellRunResult {
  exitCode?: number
  cancelled: boolean
  timedOut: boolean
  minimized?: MinimizerResult
  workingDir?: string
  fsObservations: Array<FsObservation>
  xdDispatches: Array<string>
}

export interface SliceResult {
  text: string
  width: number
}

export declare function sliceWithWidth(line: string, startCol: number, length: number, strict: boolean | undefined | null, tabWidth: number): SliceResult

export interface SpellingRange {
  start: number
  length: number
}

export declare function structuredPatchHunks(oldText: string, newText: string, context?: number | undefined | null): Array<PatchHunk>

export declare function summarizeCode(options: SummaryOptions): SummaryResult

export interface SummaryOptions {
  code: string
  lang?: string
  path?: string
  minBodyLines?: number
  minCommentLines?: number
  unfoldUntilLines?: number
  unfoldLimitLines?: number
}

export interface SummaryResult {
  language?: string
  parsed: boolean
  elided: boolean
  totalLines: number
  segments: Array<SummarySegment>
}

export interface SummarySegment {
  kind: string
  startLine: number
  endLine: number
  text?: string
}

export declare function supportsLanguage(lang: string): boolean

export declare function truncateToWidth(text: string, maxWidth: number, ellipsisKind: Ellipsis | undefined | null, pad: boolean | undefined | null, tabWidth: number): string

export declare function vectorIndexTopK(matrix: Float32Array, dimensions: number, query: Float64Array, limit: number): VectorTopK

export interface VectorTopK {
  indices: Uint32Array
  scores: Float64Array
}

export declare function visibleWidth(text: string, tabWidth: number): number

export interface WorkProfile {
  folded: string
  summary: string
  svg?: string
  totalMs: number
  sampleCount: number
}

export declare function wrapTextWithAnsi(text: string, width: number, tabWidth: number): Array<string>
