#![allow(clippy::trailing_empty_array, reason = "generated by napi macro")]
#![allow(clippy::trivially_copy_pass_by_ref, reason = "napi env idiom")]
#![feature(alloc_error_hook)]

pub mod appearance;
pub mod ast;
pub mod block;
pub mod clipboard;
pub mod crash_handler;
pub mod desktop;
pub mod devicecheck;
pub mod diff;
pub mod fd;
pub mod file_lock;
pub mod glob;
pub mod glob_util;
pub mod grep;
pub mod highlight;
pub mod html;
pub mod iofs;
pub mod js;
pub mod keys;

pub mod pdf;
pub mod sixel;
pub mod spelling;
pub mod utok;
pub use pi_ast::language;

pub mod power;

pub mod iso;
pub mod prof;
pub mod ps;
pub mod pty;
pub mod shell;
pub mod summary;
pub mod task;

pub mod text;
pub mod tokens;
pub mod tty_writer;
pub(crate) mod utils;
pub mod vectors;
pub mod workspace;

use napi_derive::{module_init, napi};

#[napi(js_name = "__piNativesV18_0_0")]
pub const fn pi_natives_version_sentinel() {}

#[module_init]
fn install_native_crash_handler() {
	crash_handler::install();
}

#[napi(js_name = "__ompInstallTokioRuntime")]
#[allow(clippy::missing_const_for_fn, reason = "napi macro is incompatible with const fn")]
pub fn proto_install_tokio_runtime() {}
