//! Native utilities exported via N-API for the Oh My Pi toolchain.
//!
//! # Overview
//! High-performance primitives for clipboard access, grep, file discovery,
//! ANSI-aware text measurement, syntax highlighting, HTML/PDF-to-Markdown
//! conversion, and terminal SIXEL encoding.
//!
//! # Example
//! ```ignore
//! use pi_natives::text::visible_width;
//!
//! let width = visible_width("hello");
//! assert_eq!(width, 5);
//! ```
//!
//! # Architecture
//! ```text
//! JS (packages/natives) -> N-API -> Rust modules (clipboard/fd/glob/grep/html/pdf/highlight/sixel/text)
//! ```

#![allow(clippy::trailing_empty_array, reason = "generated by napi macro")]
#![allow(clippy::trivially_copy_pass_by_ref, reason = "napi env idiom")]
#![feature(alloc_error_hook)]

pub mod appearance;
pub mod ast;
pub mod block;
pub mod clipboard;
pub mod crash_handler;
pub mod desktop;
pub mod devicecheck;
pub mod diff;
pub mod fd;
pub mod file_lock;
pub mod glob;
pub mod glob_util;
pub mod grep;
pub mod highlight;
pub mod html;
pub mod iofs;
pub mod js;
pub mod keys;
/// PDF inspection and Markdown conversion.
pub mod pdf;
pub mod sixel;
pub mod spelling;
pub mod utok;
pub use pi_ast::language;

pub mod power;

pub mod iso;
pub mod prof;
pub mod ps;
pub mod pty;
pub mod shell;
pub mod summary;
pub mod task;
#[cfg(test)]
pub(crate) mod testing;
pub mod text;
pub mod tokens;
pub mod tty_writer;
pub(crate) mod utils;
pub mod vectors;
pub mod workspace;

use napi_derive::{module_init, napi};

/// Version sentinel — exists solely so the JS loader can prove at load time
/// that the `.node` file on disk is from the same package release as the
/// `index.js` ESM wrapper invoking it.
///
/// The `js_name` is bumped by `scripts/release.ts` to match the new
/// `Cargo.toml` / `package.json` version on every release. The JS loader
/// computes the expected name from `package.json#version` and refuses to use
/// a `.node` that doesn't expose it, turning the silent
/// `<sym> is not a function` crash from a locked-file update (the canonical
/// Windows `bun install -g` failure mode) into a clear load-time error.
///
/// Bump policy: `__piNativesV{major}_{minor}_{patch}` — non-alphanumerics in
/// the version string are mapped to `_` to keep it a valid JS identifier.
/// MUST stay in sync with `VERSION_SENTINEL_EXPORT` in
/// `packages/natives/native/index.js` (which derives the name from
/// `package.json#version`).
#[napi(js_name = "__piNativesV18_0_0")]
pub const fn pi_natives_version_sentinel() {}

/// Native module entry point: install crash diagnostics before any tool can
/// invoke a panicking or allocating native call. This runs during `.node`
/// load, while the dynamic-loader lock is held, so it MUST NOT spawn threads;
/// napi-rs materializes its async runtime lazily on first use on every
/// platform.
#[module_init]
fn install_native_crash_handler() {
	crash_handler::install();
}

/// Retained as a stable cross-platform no-op hook.
///
/// The JS loader calls this export once, synchronously, right after `dlopen`
/// returns. It previously installed a Windows-only bounded Tokio runtime and
/// Rayon pool; every supported platform now uses napi-rs's default lazy
/// runtime, but the symbol stays so existing JS callers keep working
/// unchanged.
#[napi(js_name = "__ompInstallTokioRuntime")]
#[allow(clippy::missing_const_for_fn, reason = "napi macro is incompatible with const fn")]
pub fn proto_install_tokio_runtime() {}
